image: registry.gitlab.com/josm/docker-library/openjdk-8-josmplugin:latest

before_script:
- export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches


###############
# Build stage #
###############

assemble:
  stage: build
  script:
  - ./gradlew assemble --stacktrace
  artifacts:
    paths:
    - build/

assemble with java 11:
  stage: build
  image: registry.gitlab.com/josm/docker-library/openjdk-11-josmplugin:latest
  script:
    - ./gradlew assemble --stacktrace
  artifacts:
    paths:
      - build/

assemble with java 12:
  stage: build
  image: registry.gitlab.com/josm/docker-library/openjdk-12-josmplugin:latest
  script:
    - ./gradlew assemble --stacktrace
  artifacts:
    paths:
      - build/
  allow_failure: true

assemble with java 13:
  stage: build
  image: registry.gitlab.com/josm/docker-library/openjdk-13-josmplugin:latest
  script:
    - ./gradlew assemble --stacktrace
  artifacts:
    paths:
      - build/
  allow_failure: true


##############
# Test stage #
##############

build:
  stage: test
  script:
  - ./gradlew build generatePot --stacktrace
  artifacts:
    paths:
    - build
  dependencies:
  - assemble

compile against min JOSM:
  stage: test
  script:
  - ./gradlew compileJava_minJosm
  dependencies:
  - assemble

compile against latest JOSM:
  stage: test
  script:
  - ./gradlew compileJava_latestJosm
  dependencies:
  - assemble

build with java 11:
  stage: test
  image: registry.gitlab.com/josm/docker-library/openjdk-11-josmplugin:latest
  script:
    - ./gradlew build --stacktrace
  dependencies:
    - assemble with java 11

build with java 12:
  stage: test
  image: registry.gitlab.com/josm/docker-library/openjdk-12-josmplugin:latest
  script:
    - ./gradlew build --stacktrace
  dependencies:
    - assemble with java 12
  allow_failure: true

build with java 13:
  stage: test
  image: registry.gitlab.com/josm/docker-library/openjdk-13-josmplugin:latest
  script:
    - ./gradlew build --stacktrace
  dependencies:
    - assemble with java 13
  allow_failure: true


################
# Deploy stage #
################

upload to transifex:
  image: registry.gitlab.com/josm/docker-library/python-transifex:latest
  stage: deploy
  environment:
    name: transifex
    url: https://www.transifex.com/josm/josm/josm-plugin_wikipedia/
  script:
  - TX_TOKEN="$TRANSIFEX_TOKEN" tx push -s --no-interactive
  dependencies:
  - build
  only:
  - master@JOSM/wikipedia

publish to / GitLab pages:
  stage: deploy
  environment:
    name: pages branch / dist directory
    url: https://gitlab.com/JOSM/wikipedia/tree/pages/dist
  script:
  - |
    echo "$SSH_PRIVATE_DEPLOY_KEY" > ~/.ssh/id_rsa
    chmod 600 ~/.ssh/id_rsa
    git clone --depth 1 --branch pages git@gitlab.com:JOSM/wikipedia.git pages
  - |
    version=`git describe --always --dirty`
    longVersion=`git describe --always --long --dirty`
    commitMessage="Release version $longVersion"
  - |
    mkdir -pv "pages/dist/$version"
    cp -v build/dist/* build/tmp/jar/MANIFEST.MF "pages/dist/$version"
    rm -fv "pages/dist/latest"
    ln -s "./$version" "pages/dist/latest"
  - |
    cd pages/
    git config user.name "Deploy with GitLab CI"
    git config user.email "incoming+JOSM/wikipedia@incoming.gitlab.com"
    git stage .
    git commit -a -m "$commitMessage"
    git push origin pages
  dependencies:
  - build
  only:
  - tags@JOSM/wikipedia

publish to / GitLab.com packages:
  stage: deploy
  environment:
    name: GitLab.com / JOSM-wikipedia packages
    url: https://gitlab.com/JOSM/wikipedia/-/packages
  script:
  - ./gradlew publishPluginPublicationToGitlabRepository
  dependencies:
  - build
  only:
  - tags@JOSM/wikipedia
