image: registry.gitlab.com/josm/docker-library/openjdk-8-josmplugin:latest

stages:
  - build
  - test
  - deploy
  - release

###############
# Build stage #
###############

assemble:
  stage: build
  script:
    - ./gradlew assemble --stacktrace
  artifacts:
    paths:
      - build/
  except:
    - schedules

assemble with java 11:
  stage: build
  image: registry.gitlab.com/josm/docker-library/openjdk-11-josmplugin:latest
  script:
    - ./gradlew assemble --stacktrace
  artifacts:
    paths:
      - build/
  except:
    - schedules

assemble with java 12:
  stage: build
  image: registry.gitlab.com/josm/docker-library/openjdk-12-josmplugin:latest
  script:
    - ./gradlew assemble --stacktrace
  artifacts:
    paths:
      - build/
  allow_failure: true
  except:
    - schedules

assemble with java 13:
  stage: build
  image: registry.gitlab.com/josm/docker-library/openjdk-13-josmplugin:latest
  script:
    - ./gradlew assemble --stacktrace
  artifacts:
    paths:
      - build/
  allow_failure: true
  except:
    - schedules


##############
# Test stage #
##############

build:
  stage: test
  script:
    - ./gradlew build generatePot --stacktrace
  artifacts:
    paths:
    - build
  dependencies:
    - assemble
  except:
    - schedules

min JOSM compile:
  stage: test
  script:
    - ./gradlew compileJava_minJosm --stacktrace
  dependencies:
    - assemble
  except:
    - schedules

latest JOSM compile:
  stage: test
  script:
    - ./gradlew compileJava_latestJosm --stacktrace
  dependencies:
    - assemble
  only:
    - schedules@JOSM/plugin/wikipedia

build with java 11:
  stage: test
  image: registry.gitlab.com/josm/docker-library/openjdk-11-josmplugin:latest
  script:
    - ./gradlew build --stacktrace
  dependencies:
    - assemble with java 11
  except:
    - schedules

build with java 12:
  stage: test
  image: registry.gitlab.com/josm/docker-library/openjdk-12-josmplugin:latest
  script:
    - ./gradlew build --stacktrace
  dependencies:
    - assemble with java 12
  allow_failure: true
  except:
    - schedules

build with java 13:
  stage: test
  image: registry.gitlab.com/josm/docker-library/openjdk-13-josmplugin:latest
  script:
    - ./gradlew build --stacktrace
  dependencies:
    - assemble with java 13
  allow_failure: true
  except:
    - schedules


################
# Deploy stage #
################

upload to transifex:
  image: registry.gitlab.com/josm/docker-library/python-transifex:latest
  stage: deploy
  environment:
    name: transifex
    url: https://www.transifex.com/josm/josm/josm-plugin_wikipedia/
  script:
    - TX_TOKEN="$TRANSIFEX_TOKEN" tx push -s --no-interactive
  dependencies:
    - build
  only:
    - master@JOSM/plugin/wikipedia
  except:
    - schedules

push GitLab.com pages branch:
  stage: deploy
  environment:
    name: GitLab.com / pages branch
    url: https://gitlab.com/JOSM/plugin/wikipedia/tree/pages/dist
  script:
    - |
      base64 -d "$SSH_PRIVATE_DEPLOY_KEY" > ~/.ssh/id_rsa
      chmod 600 ~/.ssh/id_rsa
      git clone --depth 1 --branch pages git@gitlab.com:JOSM/plugin/wikipedia.git pages
    - |
      version=`git describe --always --dirty`
      longVersion=`git describe --always --long --dirty`
      commitMessage="Release version $longVersion"
    - |
      mkdir -pv "pages/dist/$version"
      cp -v build/dist/* build/tmp/jar/MANIFEST.MF "pages/dist/$version"
      rm -fv "pages/dist/latest"
      ln -s "./$version" "pages/dist/latest"
    - |
      cd pages/
      git config user.name "Deploy with GitLab CI"
      git config user.email "incoming+josm-plugin-wikipedia-6702380-issue-@incoming.gitlab.com"
      git stage .
      git commit -a -m "$commitMessage"
      git push origin pages
  dependencies:
    - build
  only:
    - tags@JOSM/plugin/wikipedia
  except:
    - schedules

package to GitLab.com:
  stage: deploy
  environment:
    name: GitLab.com / Maven packages
    url: https://gitlab.com/JOSM/plugin/wikipedia/-/packages
  script:
    - ./gradlew publishAllPublicationsToGitlabRepository
  dependencies:
    - build
  only:
    - tags@JOSM/plugin/wikipedia
  except:
    - schedules


#################
# Release stage #
#################

release to Gitlab.com:
  stage: release
  environment:
    name: GitLab.com / Releases
    url: https://gitlab.com/JOSM/plugin/wikipedia/-/releases
  script:
    - ./gradlew releaseToGitlab
  dependencies:
    - package to GitLab.com
  only:
    - tags@JOSM/plugin/wikipedia
  except:
    - schedules
